---
version: '3'
services:
  submit-connectors:
    build: kafka-connect/connector-builder
    hostname: submit-connectors
    container_name: submit-connectors
    volumes:
      - ./scripts/submit-connector.sh:/usr/bin/submit-connector.sh
      - ./kafka-connect/connectors:/connectors
    command:
      - bash
      - -c
      - |
        for connector in /connectors/*.json; do submit-connector.sh $${connector} connect; done